### ISSUE TITLE
Can't build vignettes

### ISSUE THREAD

**Issue by krietsch** [picardis/nestR#16]
Hi Simona,

the install_github function does not build the vignettes like it is written in the README. It works with: 

`devtools::install_github("picardis/nestR", build = TRUE, build_opts = c("--no-resave-data", "--no-manual"))`

However, I still get a error message and it does not manage to build the vignettes:

```
Warning in grepl(e, allfiles, perl = TRUE, ignore.case = TRUE) :
     PCRE pattern compilation error
   	'nothing to repeat'
   	at '*/img*.jpg'
   Error in grepl(e, allfiles, perl = TRUE, ignore.case = TRUE) : 
     invalid regular expression '*/img*.jpg'
   Execution halted
Error in processx::run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  : 
  System command error
```

Hope you can help.

Thanks,
Hannes

**Comment by LaurieMaynard** [comment]
I tried as well and it doesn't work for me either. Would it be possible to have a pdf version meanwhile? Thank you

**Comment by picardis** [comment]
Hi! 

I am trying to fix the error with the vignette. Meanwhile, here is a link to download a pdf version: https://drive.google.com/open?id=1BkGEGhg6EMSmWh_132OsrtJSHcU3pQfG

Thanks for letting me know!

**Comment by picardis** [comment]
Issue with vignette is resolved. Install using remotes::install_github("picardis/nestR", build_opts = "") and load vignette using vignette("nestR"). Everything should work now, if you try it and it works let me know, I'd appreciate it! Or also if it doesn't :)

**Comment by katedd** [comment]
Hello, I tried installing as you suggested but still get:
Warning message:
vignette ‘nestR’ not found
